name: Deploy to GitHub Pages

on:
  push:
    branches: 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: build
        env:
          # BASE_PATH: '/${{ github.event.repository.name }}' # Default GitHub Pages
          EVIDENCE_SOURCE__fukagawa_lake__database: "fukagawa_lake_dbt"
          EVIDENCE_SOURCE__fukagawa_lake__token: ${{ secrets.EVIDENCE_SOURCE__fukagawa_lake__token }}
          EVIDENCE_SOURCE__md_estat_catalog__database: "estat_api"
          EVIDENCE_SOURCE__md_estat_catalog__token: ${{ secrets.EVIDENCE_SOURCE__md_estat_catalog__token }}
        run: |
          npm run sources
          npm run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          # path: 'build/${{ github.event.repository.name }}'  # Default GitHub Pages
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
